// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import '@hotwired/turbo-rails'
import 'controllers'
import 'custom/bootstrap'
import 'custom/i18n'
import 'custom/translations'
import 'custom/menu'
import 'custom/product_detail'
import 'admin/users'
import 'custom/cart'
import 'custom/checkout'
